"""Full 30-qubit Qiskit training: process-parallel, exact per-instance shifts.

A circuit is built once per geometry call; only the one shifted primitive
rotation is replaced. No gate, wire, parameter, or derivative is dropped.
"""
import os
for _name in ('OMP_NUM_THREADS','OPENBLAS_NUM_THREADS','MKL_NUM_THREADS','NUMEXPR_NUM_THREADS'):
    os.environ[_name]='1'
import argparse,copy,csv,fcntl,hashlib,json,multiprocessing as mp,pickle,signal,time,traceback
from concurrent.futures import ProcessPoolExecutor,as_completed
from pathlib import Path
import numpy as np
import psutil
from qiskit import QuantumCircuit,qpy
from qiskit.quantum_info import Pauli
from qiskit_aer import AerSimulator
from .statevector import settings, require_memory
from .circuit import instances,parameter_keys
from .revision import primitive_manifest,audit_instances,audit_templates,build_block_circuit
from .benchmark002 import corrected_templates,audit_angles
from .data import load_panel,features,encode_features,fit_normalizer,PAIRS,TRIPLES
from . import mlp_full
from .experiment import versions


def atom_json(path,obj):
    path=Path(path);tmp=path.with_suffix(path.suffix+'.tmp')
    tmp.write_text(json.dumps(obj,indent=2,default=lambda v:v.tolist() if isinstance(v,np.ndarray) else v.item()))
    os.replace(tmp,path)


def save_state(path,state):
    path=Path(path);tmp=path.with_suffix('.tmp')
    with tmp.open('wb') as f:pickle.dump(state,f,protocol=5);f.flush();os.fsync(f.fileno())
    os.replace(tmp,path)


def load_state(path):
    # Checkpoints are generated by this trusted local experiment only.
    with Path(path).open('rb') as f:return pickle.load(f)


class FastSimulator:
    def __init__(self):
        self.sim=AerSimulator(**settings())
        self.calls=0

    def compile(self,gates):
        qc=QuantumCircuit(30);rotations={}
        for p in primitive_manifest(gates):
            if p['params']:
                assert p['name'] in ('rx','ry','rz') and p['group'] not in rotations
                rotations[p['group']]=len(qc.data)
            getattr(qc,p['name'])(*p['params'],*p['qubits'])
        assert len(rotations)==len(gates)
        for axis in ('X','Z'):
            for q in range(30):qc.save_expectation_value(Pauli(axis),[q],label=f'{axis}{q}')
        return qc,rotations

    def evaluate(self,qc):
        require_memory()
        result=self.sim.run(qc,shots=1,seed_simulator=916).result();self.calls+=1
        if not result.success:raise RuntimeError(str(result.status))
        z=np.array([result.data(0)[f'{a}{q}'] for a in ('X','Z') for q in range(30)],float)
        if not np.isfinite(z).all():raise FloatingPointError('Nonfinite quantum readout')
        return z

    def compute(self,gates,keys,gradient):
        qc,positions=self.compile(gates);z=self.evaluate(qc)
        if not gradient:return z,None
        jac=np.zeros((60,len(keys)));keyidx={k:i for i,k in enumerate(keys)}
        for group,g in enumerate(gates):
            if g['parameter'] is None or g['coefficient']==0:continue
            pos=positions[group];original=qc.data[pos];values=[]
            try:
                for sign in (1,-1):
                    op=original.operation.copy();op.params=[g['angle']+sign*np.pi/2]
                    qc.data[pos]=original.replace(operation=op);values.append(self.evaluate(qc))
            finally:qc.data[pos]=original
            jac[:,keyidx[g['parameter']]]+=g['coefficient']*.5*(values[0]-values[1])
        if not np.isfinite(jac).all():raise FloatingPointError('Nonfinite quantum Jacobian')
        return z,jac


_WORK={}
def worker_init(run):
    run=Path(run);meta=json.loads((run/'plan.json').read_text())
    with np.load(run/'dataset.npz') as ar:arrays={k:ar[k] for k in ar.files}
    _WORK.update(meta=meta,arrays=arrays,sim=FastSimulator())


def worker_task(task):
    idx,theta,gradient=task;start=time.perf_counter();sim=_WORK['sim'];before=sim.calls
    f={k:_WORK['arrays'][k][idx] for k in ('x1','x2','x3','w2','w3')}
    g=instances(_WORK['meta']['templates'],f,theta)
    z,jac=sim.compute(g,_WORK['meta']['keys'],gradient)
    return dict(index=idx,z=z,jacobian=jac,seconds=time.perf_counter()-start,
                calls=sim.calls-before,pid=os.getpid(),rss_bytes=psutil.Process().memory_info().rss)


def pool_for(run,workers):
    require_memory(workers)
    return ProcessPoolExecutor(max_workers=workers,mp_context=mp.get_context('spawn'),initializer=worker_init,initargs=(str(run),))


def collect(pool,indices,theta,gradient,run=None,context='probe'):
    start=time.perf_counter();futures={pool.submit(worker_task,(int(i),theta,gradient)):j for j,i in enumerate(indices)}
    rows=[None]*len(indices)
    for fut in as_completed(futures,timeout=1800):rows[futures[fut]]=fut.result()
    if run is not None:
        with (Path(run)/'quantum_tasks.jsonl').open('a') as f:
            f.write(json.dumps(dict(context=context,wall_seconds=time.perf_counter()-start,
                instances=[{k:v for k,v in r.items() if k not in ('z','jacobian')} for r in rows]))+'\n')
    return np.array([r['z'] for r in rows]),np.array([r['jacobian'] for r in rows]) if gradient else None,rows


def half_sample(panel,seed=916):
    rng=np.random.default_rng(seed);cats=sorted(set(panel['category']));counts=np.array([sum(panel['category']==c) for c in cats])
    quotas=counts//2
    for j in np.argsort(-(counts/2-quotas),kind='stable')[:1750-int(sum(quotas))]:quotas[j]+=1
    selected=[]
    for c,n in zip(cats,quotas):selected.extend(rng.permutation(np.flatnonzero(panel['category']==c))[:n].tolist())
    return np.array(sorted(selected)),dict(zip(cats,map(int,quotas)))


def prepare(run,full=False):
    run.mkdir(parents=True,exist_ok=False)
    base=Path('models/initialization');source=json.loads((base/'circuit_seed.json').read_text());radii=json.loads((base/'radii.json').read_text())
    original=load_panel(split='train')
    if full:
        train=original;categories={str(c):int(sum(original['category']==c)) for c in sorted(set(original['category']))}
    else:
        indices,categories=half_sample(original);train=load_panel(original['sample_id'][indices])
    val=load_panel(split='validation');norm=fit_normalizer(train)
    ntrain=len(train['sample_id']);nval=len(val['sample_id']);total=ntrain+nval
    templates=corrected_templates(source['templates']);audit_templates(templates);keys=parameter_keys(templates)
    arrays={};panels=[train,val]
    for k in ('sample_id','energy_ev'):arrays[k]=np.concatenate([p[k] for p in panels])
    ff=encode_features(features(np.concatenate([p['positions_angstrom'] for p in panels]),**radii),norm)
    for k in ('x1','x2','x3','w2','w3'):arrays[k]=ff[k]
    arrays['sample_id']=arrays['sample_id'].astype(str)
    arrays['y']=(arrays['energy_ev']-norm['energy_mean_ev'])/norm['energy_scale_ev']
    np.savez(run/'dataset.npz',**arrays)
    plan=dict(train=ntrain,validation=nval,test_labels_accessed=False,train_ids=list(train['sample_id']),
       validation_ids=list(val['sample_id']),sample_seed=916,category_quotas=categories,
       templates=templates,keys=keys,normalizer=norm,radii=radii,widths=[60,64,32,1],mlp_parameters=6017,
       joint_epochs=10,batch_size=64,quantum_lr=.003,mlp_lr=.001,gradient='all48_exact_per_gate_parameter_shift',
       quantum_initial_source=str(base/'circuit_seed.json'),encoding_min_abs_angle=.1,
       checkpoint='atomic latest after every batch; immutable epoch_NNN after full validation; full optimizer/RNG state',
       plan_b=dict(check_after_joint_epochs=10,all_shared_abs_below=.1,
                   action='record trigger and preserve joint result; separate classical-only stage requires explicit epoch budget',
                   not_triggered_by='validation loss alone or weighted gate angles'),
       backend=settings(),versions=versions(),cpu_count=os.cpu_count(),available_cpus=sorted(os.sched_getaffinity(0)))
    atom_json(run/'plan.json',plan)
    rng=np.random.default_rng(917);theta=source['theta'].copy()
    state=dict(schema=1,plan=plan,epoch=0,next_batch=0,order=None,rng_state=rng.bit_generator.state,
       theta=theta,quantum_adam=dict(step=0,m=np.zeros(len(keys)),v=np.zeros(len(keys))),
       network=mlp_full.initialize(plan['widths']),history=[],best_rmse=None,global_batch=0)
    save_state(run/'initial.pkl',state);save_state(run/'latest.pkl',state)
    records=[];blocks=0
    for i in range(total):
        f={k:arrays[k][i] for k in ('x1','x2','x3','w2','w3')};g=instances(templates,f,theta)
        audit_instances(g,templates);blocks+=len(audit_angles(g,f))
        row=dict(sample_id=str(arrays['sample_id'][i]),split='train' if i<ntrain else 'validation')
        for b,name,combos in ((2,'pairs',PAIRS),(3,'triples',TRIPLES)):
            row[name]=[dict(molecules=list(map(int,c)),weight=float(w)) for c,w in zip(combos,f[f'w{b}']) if w>0]
        records.append(row)
    atom_json(run/'interaction_selection.json',records)
    atom_json(run/'preparation_audit.json',dict(passed=True,geometries=total,encoding_blocks=blocks,encoding_min_abs_angle=.1,
       same_block_angles=True,structure_unchanged=True,trainable_bindings_unchanged=True))
    atom_json(run/'status.json',dict(status='prepared_pending_performance_probe',epoch_completed=0))
    print(json.dumps(dict(status='prepared',train=ntrain,validation=nval,categories=categories,encoding_blocks=blocks)),flush=True)


def accuracy(net,z,y,scale):
    residual=mlp_full.predict(net,z)-y
    return dict(mse=float(np.mean(residual**2)),rmse_ev=float(np.sqrt(np.mean(residual**2))*scale),
                mae_ev=float(np.mean(abs(residual))*scale))


def evaluate_all(pool,state,run):
    plan=state['plan'];theta=state['theta'];zs=[];ntrain=plan['train'];total=ntrain+plan['validation']
    for start in range(0,total,128):
        z,_,_=collect(pool,range(start,min(start+128,total)),theta,False,run,'metrics')
        zs.extend(z)
    z=np.array(zs)
    with np.load(Path(run)/'dataset.npz') as a:y=a['y']
    row=dict(epoch=state['epoch'],stage='joint',global_batch=state['global_batch'],quantum_max_abs=float(max(abs(v) for v in theta.values())),
             quantum_l2=float(np.linalg.norm(list(theta.values()))),
             train=accuracy(state['network'],z[:ntrain],y[:ntrain],plan['normalizer']['energy_scale_ev']),
             validation=accuracy(state['network'],z[ntrain:],y[ntrain:],plan['normalizer']['energy_scale_ev']))
    return row


def update_joint(state,z,jac,y,qgrad=None):
    plan=state['plan'];loss,grad,dz=mlp_full.backward(state['network'],z,y)
    if qgrad is None:qgrad=np.einsum('ni,nij->j',dz,jac)
    if not np.isfinite(qgrad).all() or not all(np.isfinite(g).all() for g in grad.values()):raise FloatingPointError('Nonfinite training gradients')
    mlp_full.adam_step(state['network'],grad,plan['mlp_lr'])
    opt=state['quantum_adam'];opt['step']+=1;t=opt['step']
    opt['m']=.9*opt['m']+.1*qgrad;opt['v']=.999*opt['v']+.001*qgrad*qgrad
    delta=plan['quantum_lr']*(opt['m']/(1-.9**t))/(np.sqrt(opt['v']/(1-.999**t))+1e-8)
    for j,k in enumerate(plan['keys']):state['theta'][k]-=float(delta[j])
    state['global_batch']+=1
    return dict(loss=loss,quantum_gradient_norm=float(np.linalg.norm(qgrad)),quantum_gradient=qgrad.tolist(),
                quantum_delta=(-delta).tolist(),mlp_gradient_norm=float(np.sqrt(sum(np.sum(g*g) for g in grad.values()))))


def history_files(run,state):
    atom_json(run/'history.json',state['history'])
    with (run/'history.csv').open('w',newline='') as f:
        wr=csv.writer(f);wr.writerow(['epoch','stage','train_mse','validation_mse','train_rmse_ev','validation_rmse_ev'])
        for r in state['history']:wr.writerow([r['epoch'],r['stage'],r['train']['mse'],r['validation']['mse'],r['train']['rmse_ev'],r['validation']['rmse_ev']])
    # Actual points only. Plot rendering is an independent delivery step.


def export_epoch(run,state):
    """Human-readable model alongside the full optimizer checkpoint."""
    plan=state['plan']
    atom_json(run/f'model_epoch_{state["epoch"]:03d}.json',dict(epoch=state['epoch'],backend=plan['backend'],templates=plan['templates'],
        theta=state['theta'],normalizer=plan['normalizer'],radii=plan['radii'],network=state['network'],
        metrics=state['history'][-1],widths=plan['widths'],checkpoint=f'epoch_{state["epoch"]:03d}.pkl'))
    if state.get('best_trained_epoch')==state['epoch']:
        atom_json(run/'best_model.json',json.loads((run/f'model_epoch_{state["epoch"]:03d}.json').read_text()))


def train(run,workers,epochs):
    run=Path(run);state=load_state(run/'latest.pkl');plan=state['plan']
    if plan.get('backend') != settings():
        raise ValueError('Checkpoint backend differs or is unrecorded; prepare a new statevector run instead of mixing training histories')
    assert epochs>=state['epoch'];plan['joint_epochs']=epochs
    with np.load(run/'dataset.npz') as a:
        y=a['y'];counts=60+18*(a['w2']>0).sum(1)+24*(a['w3']>0).sum(1)
    from .parallel_chunks import full_gradient
    assert plan['train_ids']==json.loads((run/'plan.json').read_text())['train_ids']
    history_files(run,state)
    atom_json(run/'runtime.json',dict(backend=settings(),pid=os.getpid(),workers=workers,aer_threads_per_worker=1,start_time=time.time(),target_epochs=epochs,
                                    available_cpus=sorted(os.sched_getaffinity(0))))
    with pool_for(run,workers) as pool:
        if not state['history']:
            row=evaluate_all(pool,state,run);state['history'].append(row);state['best_rmse']=row['validation']['rmse_ev']
            save_state(run/'epoch_000.pkl',state);save_state(run/'best.pkl',state);save_state(run/'latest.pkl',state);history_files(run,state);export_epoch(run,state)
            print('INITIAL '+json.dumps(row),flush=True)
        while state['epoch']<epochs:
            started=time.monotonic()
            if state['order'] is None:
                rng=np.random.default_rng();rng.bit_generator.state=state['rng_state'];state['order']=rng.permutation(plan['train'])
                state['rng_state']=rng.bit_generator.state;state['next_batch']=0;save_state(run/'latest.pkl',state)
            batches=[state['order'][i:i+plan['batch_size']] for i in range(0,plan['train'],plan['batch_size'])]
            for batch in range(state['next_batch'],len(batches)):
                idx=batches[batch]
                atom_json(run/'status.json',dict(status='joint_training',epoch=state['epoch']+1,epoch_completed=state['epoch'],
                        batch=batch+1,batches=len(batches),workers=workers,global_batch=state['global_batch'],heartbeat=time.time()))
                before=time.monotonic();z,_,forward_rows=collect(pool,idx,state['theta'],False,run,f'epoch{state["epoch"]+1}/batch{batch+1}/forward')
                _,_,dz=mlp_full.backward(state['network'],z,y[idx])
                qgrad,rows=full_gradient(pool,idx,state['theta'],dz,counts,run,f'epoch{state["epoch"]+1}/batch{batch+1}/gradient')
                gradients=update_joint(state,z,None,y[idx],qgrad=qgrad);state['next_batch']=batch+1
                save_state(run/'latest.pkl',state)
                log=dict(epoch=state['epoch']+1,batch=batch+1,global_batch=state['global_batch'],seconds=time.monotonic()-before,
                         calls=sum(r['calls'] for r in rows+forward_rows),**gradients)
                with (run/'batches.jsonl').open('a') as f:f.write(json.dumps(log)+'\n')
                print('BATCH '+json.dumps({k:v for k,v in log.items() if k not in ('quantum_gradient','quantum_delta')}),flush=True)
            state['epoch']+=1;state['order']=None;state['next_batch']=0
            row=evaluate_all(pool,state,run);row['epoch_seconds_this_session']=time.monotonic()-started
            state['history'].append(row)
            overall_improved=row['validation']['rmse_ev']<state['best_rmse']
            if overall_improved:state['best_rmse']=row['validation']['rmse_ev']
            if row['validation']['rmse_ev']<state.get('best_trained_rmse',float('inf')):
                state['best_trained_rmse']=row['validation']['rmse_ev'];state['best_trained_epoch']=state['epoch']
                save_state(run/'best_trained.pkl',state)
                atom_json(run/'best_selection.json',dict(epoch=state['epoch'],validation_rmse_ev=state['best_trained_rmse'],checkpoint='best_trained.pkl',criterion='minimum validation RMSE over completed trained epochs; ties retain earlier epoch',test_labels_accessed=False))
            if overall_improved:save_state(run/'best.pkl',state)
            save_state(run/f'epoch_{state["epoch"]:03d}.pkl',state);save_state(run/'latest.pkl',state);history_files(run,state);export_epoch(run,state)
            print('EPOCH '+json.dumps(row),flush=True)
    decision=dict(all_shared_abs_below=.1,maximum_abs=float(max(abs(v) for v in state['theta'].values())),
       triggered=all(abs(v)<.1 for v in state['theta'].values()),joint_epochs_completed=state['epoch'],
       action='joint budget complete; classical-only stage budget pending if triggered')
    atom_json(run/'plan_b_decision.json',decision)
    atom_json(run/'status.json',dict(status='joint_completed',epoch_completed=state['epoch'],best_validation_rmse_ev=state['best_rmse'],
        best_trained_epoch=state.get('best_trained_epoch'),best_trained_rmse_ev=state.get('best_trained_rmse'),plan_b=decision))


def probe(run,workers_list):
    run=Path(run);state=load_state(run/'initial.pkl');theta=state['theta'];rows=[]
    # Identical geometry IDs and fixed parameters for all configurations.
    with np.load(run/'dataset.npz') as a:
        count=60+18*(a['w2'][:state['plan']['train']]>0).sum(1)+24*(a['w3'][:state['plan']['train']]>0).sum(1)
    order=np.argsort(count,kind='stable');indices=[int(order[int(x)]) for x in np.linspace(0,state['plan']['train']-1,64)]
    for workers in workers_list:
        st=time.monotonic()
        with pool_for(run,workers) as pool:
            collect(pool,indices,theta,False)
            start=time.monotonic();_,jac,rr=collect(pool,indices,theta,True,run,f'performance/{workers}')
            elapsed=time.monotonic()-start
        row=dict(workers=workers,geometries=64,seconds=elapsed,geometries_per_second=64/elapsed,
                 quantum_calls=sum(x['calls'] for x in rr),max_worker_rss=max(x['rss_bytes'] for x in rr),including_startup_seconds=time.monotonic()-st)
        rows.append(row);np.save(run/f'probe_jacobian_{workers}.npy',jac)
        atom_json(run/'performance_probe.json',rows);print('PERFORMANCE '+json.dumps(row),flush=True)
    selected=max(rows,key=lambda r:r['geometries_per_second'])['workers']
    reference=np.load(run/f'probe_jacobian_{workers_list[0]}.npy')
    for workers in workers_list:np.testing.assert_allclose(reference,np.load(run/f'probe_jacobian_{workers}.npy'),atol=1e-12,rtol=1e-12)
    atom_json(run/'selected_workers.json',dict(workers=selected,identical_gradients_across_workers=True))


def main():
    p=argparse.ArgumentParser();p.add_argument('mode',choices=['prepare','probe','train']);p.add_argument('--run',required=True)
    p.add_argument('--workers',type=int,default=1);p.add_argument('--worker-options',default='1');p.add_argument('--epochs',type=int,default=10)
    p.add_argument('--full',action='store_true',help='Use all original training data for a new run')
    a=p.parse_args();run=Path(a.run)
    try:
        if a.mode=='prepare':prepare(run,full=a.full)
        elif a.mode=='probe':probe(run,list(map(int,a.worker_options.split(','))))
        else:
            with (run/'training.lock').open('a') as lock:
                fcntl.flock(lock,fcntl.LOCK_EX|fcntl.LOCK_NB)
                train(run,a.workers,a.epochs)
    except BaseException as exc:
        if run.exists():atom_json(run/'failure.json',dict(type=type(exc).__name__,error=str(exc),traceback=traceback.format_exc(),time=time.time()))
        raise

if __name__=='__main__':
    # Use canonical module globals in spawned workers and chunk-task imports.
    from water10_v4.parallel_training import main as entry
    entry()
